### ISSUE TITLE
Unknown interaction

### ISSUE THREAD

**Issue by 63poopy** [WillTDA/Discord.js-Akinator-Package-Dev#18]
This error pops up when i use the buttons
```js
Discord.js Akinator Error:
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/runner/Bot/node_modules/discord.js/src/rest/RequestHandler.js:298:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/runner/Bot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async ButtonInteraction.update (/home/runner/Bot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:210:5)
    at async /home/runner/Bot/node_modules/discord.js-akinator/src/index.js:325:45
    at async module.exports (/home/runner/Bot/node_modules/discord.js-akinator/src/index.js:289:13) {
  method: 'post',
  path: '/interactions/899659054857723965/aW50ZXJhY3Rpb246ODk5NjU5MDU0ODU3NzIzOTY1OmY0MkpTQlJzMnJxMGlrOWU4ZXM5NzIwdjRmTlZmdDB6ZDdqUnBVeGZ2WnQ3N09yQ2hpTHUyN0dKRUp6eVBtSW9SSHZtQkxmWlRGNFJwZmhsdWdFc0JBTFg4WmY3VTZ0cXJPVG0zeUZ1NDFQTmpZS0I5c3N2UGxTcGJyYUk3YklX/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 7, data: [Object] }, files: [] }
}
```

**Comment by 3061LRTAGSPKJMORMRT** [comment]
Usually this bug occurs if you don't do anything within 3 seconds.

@WillTDA Might be for you

**Comment by BeastBoyADI** [comment]
Just edit the source code and edit to add deferUpdate and change some stuffs accordingly so it will be fixed. I have fixed it by just adding .deferUpdate() and changing response.update to akiMessage.edit

**Comment by 3061LRTAGSPKJMORMRT** [comment]
Not all people use slash commands, so it would be a pain to make an `if` check to see if a message or a command interaction object is given. Not impossible tho. Maybe we could add a function or smth but yea

**Comment by BeastBoyADI** [comment]
I was talking about button interaction
